# Generated by Django 5.2.14 on 2026-05-07 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Điểm số')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian hoàn thành')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Từ vựng')),
                ('meaning', models.CharField(max_length=255, verbose_name='Nghĩa')),
                ('example', models.TextField(blank=True, verbose_name='Ví dụ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='Đã thuộc')),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vocabulary')),
            ],
        ),
    ]
