# Generated by Django 5.2.14 on 2026-05-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Chủ đề', 'verbose_name_plural': 'Chủ đề'},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcard'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['word'], 'verbose_name': 'Từ vựng', 'verbose_name_plural': 'Từ vựng'},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần ôn tập'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='ipa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phiên âm IPA'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Danh từ'), ('verb', 'Động từ'), ('adjective', 'Tính từ'), ('adverb', 'Trạng từ'), ('preposition', 'Giới từ'), ('conjunction', 'Liên từ'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Từ loại'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='vocabulary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='core.vocabulary'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='core.category', verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example',
            field=models.TextField(blank=True, verbose_name='Câu ví dụ'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='meaning',
            field=models.CharField(max_length=255, verbose_name='Nghĩa tiếng Việt'),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Số câu đúng')),
                ('total', models.IntegerField(default=5, verbose_name='Tổng số câu')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Phần trăm đúng')),
                ('answers_detail', models.JSONField(blank=True, default=dict, verbose_name='Chi tiết đáp án')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian hoàn thành')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Chủ đề')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Kết quả kiểm tra',
                'verbose_name_plural': 'Kết quả kiểm tra',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bộ từ vựng')),
                ('source_text', models.TextField(blank=True, verbose_name='Đoạn văn nguồn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_sets', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bộ từ vựng',
                'verbose_name_plural': 'Bộ từ vựng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocab_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.vocabset', verbose_name='Bộ từ vựng'),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
