# Generated by Django 5.2.14 on 2026-05-13 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_flashcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='easiness_factor',
            field=models.FloatField(default=2.5, verbose_name='Hệ số dễ (EF)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=0, verbose_name='Khoảng thời gian (ngày)'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày ôn tập tiếp theo'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetition_count',
            field=models.IntegerField(default=0, verbose_name='Số lần lặp lại liên tiếp'),
        ),
    ]
