# Generated by Django 5.2.14 on 2026-05-28 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flashcard_easiness_factor_flashcard_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabset',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.vocabulary', verbose_name='Từ vựng'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('user', 'vocabulary')},
        ),
    ]
