# Generated by Django 5.2.14 on 2026-05-28 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_owner_vocabset_user_category_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài nghe')),
                ('audio_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn file âm thanh')),
                ('transcript', models.TextField(blank=True, verbose_name='Bản ghi lời thoại (Transcript)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bài nghe (Listening)',
                'verbose_name_plural': 'Bài nghe (Listening)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài đọc')),
                ('text_content', models.TextField(verbose_name='Nội dung văn bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bài đọc (Reading)',
                'verbose_name_plural': 'Bài đọc (Reading)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài nói')),
                ('prompt_text', models.TextField(verbose_name='Câu hỏi phản xạ/chủ đề nói')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bài nói (Speaking)',
                'verbose_name_plural': 'Bài nói (Speaking)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_listening', models.PositiveIntegerField(default=0, verbose_name='Mục tiêu Nghe (Listening)')),
                ('target_speaking', models.PositiveIntegerField(default=0, verbose_name='Mục tiêu Nói (Speaking)')),
                ('target_reading', models.PositiveIntegerField(default=0, verbose_name='Mục tiêu Đọc (Reading)')),
                ('target_writing', models.PositiveIntegerField(default=0, verbose_name='Mục tiêu Viết (Writing)')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Ngày thi dự kiến')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin học viên',
                'verbose_name_plural': 'Thông tin học viên',
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing')], max_length=20, verbose_name='Kỹ năng')),
                ('task_title', models.CharField(max_length=255, verbose_name='Tiêu đề bài tập')),
                ('score_achieved', models.FloatField(blank=True, null=True, verbose_name='Điểm số đạt được')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hoàn thành')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Lịch sử nộp bài',
                'verbose_name_plural': 'Lịch sử nộp bài',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('prompt_text', models.TextField(verbose_name='Đề bài luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bài viết (Writing)',
                'verbose_name_plural': 'Bài viết (Writing)',
                'ordering': ['-created_at'],
            },
        ),
    ]
