# Generated by Django 5.2.14 on 2026-05-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listeningtrack_readingpassage_speakingprompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Trắc nghiệm chọn một (Multiple Choice)'), ('tfng', 'Đúng / Sai / Không nhắc tới (True / False / Not Given)')], default='multiple_choice', max_length=30, verbose_name='Loại câu hỏi')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Danh sách lựa chọn (dạng mảng JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Đáp án đúng')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.readingpassage', verbose_name='Bài đọc')),
            ],
            options={
                'verbose_name': 'Câu hỏi đọc hiểu',
                'verbose_name_plural': 'Câu hỏi đọc hiểu',
            },
        ),
    ]
