# Generated by Django 5.2.14 on 2026-05-28 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_readingquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Trắc nghiệm chọn một (Multiple Choice)'), ('fill_blank', 'Điền vào chỗ trống (Fill in the Blank)')], default='multiple_choice', max_length=30, verbose_name='Loại câu hỏi')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Danh sách lựa chọn (dạng mảng JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Đáp án đúng')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.listeningtrack', verbose_name='Bài nghe')),
            ],
            options={
                'verbose_name': 'Câu hỏi nghe hiểu',
                'verbose_name_plural': 'Câu hỏi nghe hiểu',
            },
        ),
    ]
