# Generated by Django 5.2.14 on 2026-06-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listeningquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='listeningtrack',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='speakingprompt',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='writingtask',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ'),
        ),
    ]
