# Generated by Django 5.2.14 on 2026-06-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_level_listeningquestion_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Câu hỏi')),
                ('options', models.JSONField(default=list, verbose_name='Danh sách lựa chọn (dạng mảng JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Đáp án đúng')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default='A1', max_length=2, verbose_name='Trình độ')),
            ],
            options={
                'verbose_name': 'Câu hỏi từ vựng',
                'verbose_name_plural': 'Câu hỏi từ vựng',
            },
        ),
    ]
