# Generated by Django 5.2.14 on 2026-06-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vocabularyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='topic',
            field=models.CharField(choices=[('people', 'People & Family'), ('school', 'School & Work'), ('home', 'Home & Surroundings'), ('food', 'Food & Drink'), ('verbs', 'Verbs & Actions'), ('adjectives', 'Adjectives & Description'), ('travel', 'Travel & Places'), ('weather', 'Weather & Seasons'), ('nature', 'Nature & Environment'), ('health', 'Health & Sports'), ('arts', 'Leisure & Arts'), ('tech', 'Technology & Media'), ('communication', 'Communication & Info'), ('professional', 'Professional & Abstract'), ('other', 'Other topics')], default='other', max_length=50, verbose_name='Chủ đề'),
        ),
    ]
