# Generated by Django 5.2.14 on 2026-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vocabulary_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='target_listening',
            field=models.FloatField(default=0.0, verbose_name='Mục tiêu Nghe (Listening)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_reading',
            field=models.FloatField(default=0.0, verbose_name='Mục tiêu Đọc (Reading)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_speaking',
            field=models.FloatField(default=0.0, verbose_name='Mục tiêu Nói (Speaking)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_writing',
            field=models.FloatField(default=0.0, verbose_name='Mục tiêu Viết (Writing)'),
        ),
    ]
